version: "3.9"

services:
  app:
    image: ghcr.io/pennstatewilkes-barre/afct-dashboard:main
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afct-app
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production

      DATABASE_URL: ${DATABASE_URL}

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: afct_user
      DB_NAME: afct

      WAIT_FOR_DB: "true"
      MIGRATE_ON_START: "true"
      SEED_ON_START: "auto"

    volumes:
      # PRIVATE uploads (not served by Next.js)
      - /opt/afct/uploads:/private/uploads

    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: afct-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: afct
      POSTGRES_USER: afct_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - /opt/afct/postgres:/var/lib/postgresql/data

    ports:
      - "5432:5432"
