import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// Generated by `npm run gen-api` (docusaurus-plugin-openapi-docs); run
// `npm run docs:api` at the repo root first to produce the spec.
import apiSidebar from './docs/api-reference/sidebar';

// One explicit sidebar so the reading order is deliberate. Doc ids are the file
// paths under docs/ without the extension.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Installation & Setup',
      items: [
        'setup/requirements',
        'setup/production',
        'setup/production/aws',
        'setup/production/linux',
        'setup/production/macos',
        'setup/production/windows',
        'setup/production/non-docker',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Student',
          items: ['student/overview', 'student/client'],
        },
        {
          type: 'category',
          label: 'Faculty',
          items: [
            {
              type: 'category',
              label: 'Course',
              link: {
                type: 'doc',
                id: 'faculty/course',
              },
              items: [
                {
                  type: 'category',
                  label: 'Assignments',
                  link: {
                    type: 'doc',
                    id: 'faculty/assignments',
                  },
                  items: ['faculty/submissions'],
                },
                'faculty/problems',
                'faculty/roster',
                'faculty/grades',
                'faculty/groups',
                'faculty/activity',
                'faculty/settings',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Administrator',
          link: {
            type: 'doc',
            id: 'guides/admin',
          },
          items: [
            'admin/courses',
            'admin/development-tests',
            'admin/submission-logs',
            'admin/system-logs',
            'admin/system-settings',
            'admin/system-status',
            'admin/user-accounts',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'reference/contributing',
        'reference/development-setup',
        'reference/conventions',
        'reference/comment-style',
        'reference/documentation-style',
        'reference/development-troubleshooting',
        'reference/creating-a-release',
        'reference/system-architecture',
        'reference/roles-and-permissions',
        'reference/login-protection',
        'reference/client-api',
        'reference/content-security-policy',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['operations/updates', 'operations/backups', 'operations/troubleshooting'],
    },
  ],

  // The generated OpenAPI reference gets its own sidebar (navbar: API Reference).
  apiReference: apiSidebar,
};

export default sidebars;
