import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The vendored KaTeX assets are generated by scripts/vendor-katex.mjs and committed. Nothing at
 * build time regenerates or checks them, so without this the failure mode is silent: a KaTeX
 * upgrade renames a face, the stylesheet points at a file that is not in the repo, and maths
 * renders in a fallback font that nobody notices until a professor says the symbols look wrong.
 */
const root = process.cwd();
const cssPath = join(root, 'public', 'katex', 'katex.min.css');
const fontsDir = join(root, 'public', 'katex', 'fonts');

const css = readFileSync(cssPath, 'utf8');
const referenced = [...css.matchAll(/url\(([^)]+)\)/g)].map((m) =>
  m[1].replace(/^["']|["']$/g, ''),
);

describe('vendored katex assets', () => {
  it('references at least one font', () => {
    // Guards the guard: a regex that silently matched nothing would make every assertion pass.
    expect(referenced.length).toBeGreaterThan(0);
  });

  it('references only files that exist', () => {
    const missing = referenced.filter((ref) => !existsSync(join(root, 'public', 'katex', ref)));
    expect(missing).toEqual([]);
  });

  it('ships no font the stylesheet never asks for', () => {
    // A stale file from a previous KaTeX version is dead weight in the repo and in every image.
    const orphans = readdirSync(fontsDir).filter((name) => !referenced.includes(`fonts/${name}`));
    expect(orphans).toEqual([]);
  });

  it('ships woff2 only, matching the documented decision', () => {
    // See scripts/vendor-katex.mjs for the browser-support assumption behind dropping woff/ttf.
    const wrongFormat = referenced.filter((ref) => !ref.endsWith('.woff2'));
    expect(wrongFormat).toEqual([]);
    expect(readdirSync(fontsDir).every((name) => name.endsWith('.woff2'))).toBe(true);
  });

  it('declares no format the vendored copy cannot satisfy', () => {
    // Upstream lists woff2/woff/truetype in one src; the script deletes the entries it no longer
    // ships. If a format() survived without its url, a browser could pick a missing file.
    expect(css).not.toMatch(/format\("(?:woff|truetype)"\)/);
  });

  it('matches the katex version installed in node_modules', () => {
    // The stylesheet has no version marker, so compare a stable structural fact instead: the
    // number of faces upstream declares. A major KaTeX bump that adds or drops one fails here.
    const installed = join(root, 'node_modules', 'katex', 'dist', 'katex.min.css');
    if (!existsSync(installed)) return; // node_modules is not guaranteed in every CI job
    const upstreamFaces = (readFileSync(installed, 'utf8').match(/@font-face/g) ?? []).length;
    const vendoredFaces = (css.match(/@font-face/g) ?? []).length;
    expect(vendoredFaces).toBe(upstreamFaces);
  });
});
