'use client';

import { useEffect, useRef, useState } from 'react';
import { Check, Copy } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { showToast } from '@/lib/toast';

import { SettingsAsideCard } from './settings-layout';

/** How long "copied" stays on the button before it offers to copy again. */
const COPIED_MS = 2000;

/**
 * The server's public address, as reference rather than as a field.
 *
 * It used to render through a read-only InputGroup, which made it look like the one thing
 * on the page you could not type into: a labelled box, a border, a cursor, and a paragraph
 * of installer instructions sitting in the middle of the editable form. It is not a
 * setting. It comes from NEXTAUTH_URL, it is fixed until the server is reconfigured, and
 * what an admin actually wants from it is to read it and paste it somewhere else.
 *
 * So: a value you can select and copy, then the two facts about it, in the rail beside the
 * settings you can really change.
 */
export function PublicAddressCard({
  configuredUrl,
  loading,
}: {
  configuredUrl: string | undefined;
  loading: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Cleared on unmount, so switching tabs mid-countdown cannot set state on a gone component.
  useEffect(() => {
    return () => {
      if (timer.current) clearTimeout(timer.current);
    };
  }, []);

  const value = loading ? 'Loading…' : (configuredUrl ?? 'Not set');
  const canCopy = !loading && !!configuredUrl;

  const copy = async () => {
    if (!configuredUrl) return;
    try {
      await navigator.clipboard.writeText(configuredUrl);
      setCopied(true);
      if (timer.current) clearTimeout(timer.current);
      timer.current = setTimeout(() => setCopied(false), COPIED_MS);
    } catch {
      // Copying can be refused (an insecure origin, a browser permission). The address is
      // on screen and selectable, so say that rather than leaving the button stuck on
      // "Copied" for something that did not happen. Same wording as the LTI tab's copy.
      setCopied(false);
      showToast.error('Could not copy. Select the address and copy it manually.');
    }
  };

  return (
    <SettingsAsideCard title="Public address">
      <div className="space-y-3">
        {/* The value on its own surface so it reads as a thing to take away, not as prose.
            bg-card because the card around it is bg-muted: on the rail the white one is the
            value. min-w-0 + break-all so a long institutional hostname wraps inside the
            288px rail instead of pushing the button out of it. */}
        <div className="bg-card flex items-start gap-2 rounded-md border p-2">
          <span className="text-foreground min-w-0 flex-1 font-mono text-sm break-all">
            {value}
          </span>
          <Button
            type="button"
            size="sm"
            variant="ghost"
            className="size-8 shrink-0"
            onClick={() => void copy()}
            disabled={!canCopy}
            // Icon-only: at 288px a "Copy" label would take a third of the row away from
            // the address. The name says which address, since the page has several URLs.
            aria-label="Copy public address"
          >
            {copied ? (
              <Check className="size-4" aria-hidden="true" />
            ) : (
              <Copy className="size-4" aria-hidden="true" />
            )}
          </Button>
        </div>

        {/* One live region for this card, so the result is announced once and the address
            itself is not read out again. */}
        <p role="status" aria-live="polite" className="sr-only">
          {copied ? 'Public address copied to the clipboard.' : ''}
        </p>

        <p className="text-muted-foreground text-xs leading-4.5">
          Used for sign-in links and redirects generated by AFCT.
        </p>

        <div className="space-y-2 border-t pt-3">
          <h3 className="text-foreground text-sm font-semibold">How to change it</h3>
          <p className="text-muted-foreground text-xs leading-4.5">
            It is set at the server level, from the <code className="font-mono">NEXTAUTH_URL</code>{' '}
            environment variable, and cannot be edited here. Re-run the installer on the server with
            the new address:
          </p>
          <p className="bg-card text-foreground rounded-md border p-2 font-mono text-xs break-all">
            sh install.sh --reconfigure
          </p>
          <p className="text-muted-foreground text-xs leading-4.5">
            or pass <code className="font-mono">APP_URL=https://new.address</code>. That rewrites
            the value, restarts the stack, and preserves your data and secrets.
          </p>
        </div>
      </div>
    </SettingsAsideCard>
  );
}

export default PublicAddressCard;
