'use client';

import { CopyableValue } from './CopyableValue';
import { SettingsAsideCard } from '@/components/settings/settings-layout';

/**
 * The server's public address, as reference rather than as a field.
 *
 * It used to render through a read-only InputGroup, which made it look like the one thing
 * on the page you could not type into: a labelled box, a border, a cursor, and a paragraph
 * of installer instructions sitting in the middle of the editable form. It is not a
 * setting. It comes from NEXTAUTH_URL, it is fixed until the server is reconfigured, and
 * what an admin actually wants from it is to read it and paste it somewhere else.
 */
export function PublicAddressCard({
  configuredUrl,
  loading,
}: {
  configuredUrl: string | undefined;
  loading: boolean;
}) {
  const value = loading ? 'Loading…' : (configuredUrl ?? 'Not set');

  return (
    <SettingsAsideCard title="Public address">
      <div className="space-y-3">
        <CopyableValue
          value={value}
          copyName="public address"
          canCopy={!loading && !!configuredUrl}
          description="Used for sign-in links and redirects generated by AFCT."
        />

        {/* Tiers, not one flat gap. Everything here used to sit 8px apart, which made a
            heading, its explanation and a command read as four equal things and the card
            longer than its content. 6px binds the heading to its own sentence; 8px
            separates the steps. */}
        <div className="space-y-2 border-t pt-3">
          <div className="space-y-1.5">
            <h3 className="text-foreground text-sm font-semibold">How to change it</h3>
            <p className="text-muted-foreground text-xs leading-4.5">
              It is set at the server level, from the{' '}
              <code className="font-mono">NEXTAUTH_URL</code> environment variable, and cannot be
              edited here. Re-run the installer on the server with the new address:
            </p>
          </div>
          <p className="bg-muted text-foreground rounded-md border px-3 py-2 font-mono text-xs break-all">
            sh install.sh --reconfigure
          </p>
          <p className="text-muted-foreground text-xs leading-4.5">
            or pass <code className="font-mono">APP_URL=https://new.address</code>. That rewrites
            the value, restarts the stack, and preserves your data and secrets.
          </p>
        </div>
      </div>
    </SettingsAsideCard>
  );
}

export default PublicAddressCard;
